pragma Singleton
import QtQuick 2.15

QtObject{
    readonly property string wisenet_viewer_logo : "qrc:/WisenetStyle/Icon/wisenet_viewer_logo.svg"

    readonly property string root_normal : "qrc:/WisenetStyle/Icon/Tree/tree_resourceroot_normal.svg"
    readonly property string group_normal : "qrc:/WisenetStyle/Icon/Tree/tree_group_normal.svg"
    readonly property string device_normal : "qrc:/WisenetStyle/Icon/Tree/tree_group_normal.svg"
    readonly property string device_disconnect : "qrc:/WisenetStyle/Icon/Tree/tree_group_normal.svg"
    readonly property string camera_normal : "qrc:/WisenetStyle/Icon/Tree/tree_camera_normal.svg"
    readonly property string camera_disconnect : "qrc:/WisenetStyle/Icon/Tree/tree_camera_disconnected_normal.svg"
    readonly property string camera_unused : "qrc:/WisenetStyle/Icon/Tree/tree_camera_unused.svg"
    readonly property string webpage : "qrc:/WisenetStyle/Icon/Tree/tree_webpage_normal.svg"
    readonly property string mediafile_root_normal : "qrc:/WisenetStyle/Icon/Tree/tree_mediafile_root_normal.svg"
    readonly property string image_file_normal : "qrc:/WisenetStyle/Icon/Tree/tree_image_file_normal.svg"
    readonly property string video_file_normal : "qrc:/WisenetStyle/Icon/Tree/tree_video_file_normal.svg"
    readonly property string layout : "qrc:/WisenetStyle/Icon/Tree/tree_layout_normal.svg"
    readonly property string layout_locked : "qrc:/WisenetStyle/Icon/Tree/tree_layout_locked_normal.svg"
    readonly property string shared_layout : "qrc:/WisenetStyle/Icon/Tree/tree_shared_layout_normal.svg"

    readonly property string root_hover : "qrc:/WisenetStyle/Icon/Tree/tree_resourceroot_over.svg"
    readonly property string group_hover : "qrc:/WisenetStyle/Icon/Tree/tree_group_over.svg"
    readonly property string device_hover : "qrc:/WisenetStyle/Icon/Tree/tree_group_over.svg"
    readonly property string device_disconnect_hover : "qrc:/WisenetStyle/Icon/Tree/tree_group_over.svg"
    readonly property string camera_hover : "qrc:/WisenetStyle/Icon/Tree/tree_camera_over.svg"
    readonly property string camera_disconnect_hover : "qrc:/WisenetStyle/Icon/Tree/tree_camera_disconnected_over.svg"
    readonly property string camera_unused_hover : "qrc:/WisenetStyle/Icon/Tree/tree_camera_unused_over.svg"
    readonly property string webpage_hover : "qrc:/WisenetStyle/Icon/Tree/tree_webpage_over.svg"
    readonly property string mediafile_root_hover : "qrc:/WisenetStyle/Icon/Tree/tree_mediafile_root_over.svg"
    readonly property string image_file_hover : "qrc:/WisenetStyle/Icon/Tree/tree_image_file_over.svg"
    readonly property string video_file_hover : "qrc:/WisenetStyle/Icon/Tree/tree_video_file_over.svg"
    readonly property string layout_hover : "qrc:/WisenetStyle/Icon/Tree/tree_layout_normal.svg"
    readonly property string layout_locked_hover : "qrc:/WisenetStyle/Icon/Tree/tree_layout_locked_normal.svg"
    readonly property string shared_layout_hover : "qrc:/WisenetStyle/Icon/Tree/tree_shared_layout_normal.svg"
    readonly property string smart_search_lock_normal : "qrc:/WisenetStyle/Icon/Tree/tree_smart_search_lock_normal.svg"
    readonly property string smart_search_lock_hover : "qrc:/WisenetStyle/Icon/Tree/tree_smart_search_lock_over.svg"
    readonly property string smart_search_lock_dim : "qrc:/WisenetStyle/Icon/Tree/tree_smart_search_lock_dim.svg"

    readonly property string user : "qrc:/WisenetStyle/Icon/Tree/setup_tree_icon_user_normal.png"
    readonly property string calendar: "qrc:/WisenetStyle/Icon/calendar.svg"

    readonly property string alarmOut: "qrc:/WisenetStyle/Icon/Event/alarmout.svg";
    readonly property string alarmIn: "qrc:/WisenetStyle/Icon/Event/alarmIn.svg";

    readonly property string tree_arrow_bottom: "qrc:/WisenetStyle/Icon/Tree/tree_arrow_bottom.svg"
    readonly property string tree_arrow_top: "qrc:/WisenetStyle/Icon/Tree/tree_arrow_top.svg"

    // Event Type
    readonly property string motionDetection: "qrc:/WisenetStyle/Icon/EventType/motion_detection_default.svg"
    readonly property string faceDetection: "qrc:/WisenetStyle/Icon/EventType/face_detection_default.svg"
    readonly property string tamperingDetection: "qrc:/WisenetStyle/Icon/EventType/tampering_detection_default.svg"
    readonly property string audioDetection: "qrc:/WisenetStyle/Icon/EventType/audio_detection_default.svg"
    readonly property string iva: "qrc:/WisenetStyle/Icon/EventType/iva_default.svg"
    readonly property string autoTracking: "qrc:/WisenetStyle/Icon/EventType/auto_tracking_default.svg"
    readonly property string defocusDetection: "qrc:/WisenetStyle/Icon/EventType/defocus_detection_default.svg"
    readonly property string fogDetection: "qrc:/WisenetStyle/Icon/EventType/fog_detection_default.svg"
    readonly property string soundClassification: "qrc:/WisenetStyle/Icon/EventType/sound_classification_default.svg"
    readonly property string alarmInput: "qrc:/WisenetStyle/Icon/EventType/alarmInput_default.svg"
    readonly property string videoloss: "qrc:/WisenetStyle/Icon/EventType/video_loss_default.svg"
    readonly property string videoAnalyticsPassing: "qrc:/WisenetStyle/Icon/EventType/video_analytics_passing_default.svg"
    readonly property string videoAnalyticsIntrusion: "qrc:/WisenetStyle/Icon/EventType/video_analytics_Intrusion_default.svg"
    readonly property string videoAnalyticsEntering: "qrc:/WisenetStyle/Icon/EventType/video_analytics_entering_default.svg"
    readonly property string videoAnalyticsExiting: "qrc:/WisenetStyle/Icon/EventType/video_analytics_exiting_default.svg"
    readonly property string videoAnalyticsAppearing: "qrc:/WisenetStyle/Icon/EventType/video_analytics_appearing_default.svg"
    readonly property string videoAnalyticsDisappearing: "qrc:/WisenetStyle/Icon/EventType/video_analytics_disappearing_default.svg"
    readonly property string videoAnalyticsLoitering: "qrc:/WisenetStyle/Icon/EventType/video_analytics_loitering_default.svg"
    readonly property string audioAnalyticsScream: "qrc:/WisenetStyle/Icon/EventType/audio_analytics_scream_default.svg"
    readonly property string audioAnalyticsGunshot: "qrc:/WisenetStyle/Icon/EventType/audio_analytics_gunshot_default.svg"
    readonly property string audioAnalyticsExplosion: "qrc:/WisenetStyle/Icon/EventType/audio_analytics_explosion_default.svg"
    readonly property string audioAnalyticsGlassBreak: "qrc:/WisenetStyle/Icon/EventType/audio_analytics_glassbreak_default.svg"
    readonly property string networkAlarmInput: "qrc:/WisenetStyle/Icon/EventType/network_alarm_input_default.svg"
    readonly property string dynamicEvent: "qrc:/WisenetStyle/Icon/EventType/dyanamic_event_default.svg"


    // MediaController Image
    readonly property string mediaController_fold_default : "qrc:/images/MediaController/timeline_fold_default.svg"
    readonly property string mediaController_fold_over : "qrc:/images/MediaController/timeline_fold_over.svg"
    readonly property string mediaController_fold_press : "qrc:/images/MediaController/timeline_fold_press.svg"
    readonly property string mediaController_open_default : "qrc:/images/MediaController/timeline_open_default.svg"
    readonly property string mediaController_open_over : "qrc:/images/MediaController/timeline_open_over.svg"
    readonly property string mediaController_open_press : "qrc:/images/MediaController/timeline_open_press.svg"
    readonly property string mediaController_prevEvent_default : "qrc:/images/MediaController/prevEvent_Default.svg"
    readonly property string mediaController_prevEvent_dim : "qrc:/images/MediaController/prevEvent_dim.svg"
    readonly property string mediaController_prevEvent_hover : "qrc:/images/MediaController/prevEvent_Hover.svg"
    readonly property string mediaController_prevEvent_press : "qrc:/images/MediaController/prevEvent_Press.svg"
    readonly property string mediaController_speedBackward_default : "qrc:/images/MediaController/speedBackward_Default.svg"
    readonly property string mediaController_speedBackward_dim : "qrc:/images/MediaController/speedBackward_dim.svg"
    readonly property string mediaController_speedBackward_hover : "qrc:/images/MediaController/speedBackward_Hover.svg"
    readonly property string mediaController_speedBackward_press : "qrc:/images/MediaController/speedBackward_Press.svg"
    readonly property string mediaController_stepBackward_default : "qrc:/images/MediaController/stepBackward_Default.svg"
    readonly property string mediaController_stepBackward_dim : "qrc:/images/MediaController/stepBackward_dim.svg"
    readonly property string mediaController_stepBackward_hover : "qrc:/images/MediaController/stepBackward_Hover.svg"
    readonly property string mediaController_stepBackward_press : "qrc:/images/MediaController/stepBackward_Press.svg"
    readonly property string mediaController_pause_default : "qrc:/images/MediaController/pause_Default.svg"
    readonly property string mediaController_pause_dim : "qrc:/images/MediaController/pause_dim.svg"
    readonly property string mediaController_pause_hover : "qrc:/images/MediaController/pause_Hover.svg"
    readonly property string mediaController_pause_press : "qrc:/images/MediaController/pause_Press.svg"
    readonly property string mediaController_play_default : "qrc:/images/MediaController/play_Default.svg"
    readonly property string mediaController_play_dim : "qrc:/images/MediaController/play_dim.svg"
    readonly property string mediaController_play_hover : "qrc:/images/MediaController/play_Hover.svg"
    readonly property string mediaController_play_press : "qrc:/images/MediaController/play_Press.svg"
    readonly property string mediaController_speedForward_default : "qrc:/images/MediaController/speedForward_Default.svg"
    readonly property string mediaController_speedForward_dim : "qrc:/images/MediaController/speedForward_dim.svg"
    readonly property string mediaController_speedForward_hover : "qrc:/images/MediaController/speedForward_Hover.svg"
    readonly property string mediaController_speedForward_press : "qrc:/images/MediaController/speedForward_Press.svg"
    readonly property string mediaController_stepForward_default : "qrc:/images/MediaController/stepForward_Default.svg"
    readonly property string mediaController_stepForward_dim : "qrc:/images/MediaController/stepForward_dim.svg"
    readonly property string mediaController_stepForward_hover : "qrc:/images/MediaController/stepForward_Hover.svg"
    readonly property string mediaController_stepForward_press : "qrc:/images/MediaController/stepForward_Press.svg"
    readonly property string mediaController_nextEvent_default : "qrc:/images/MediaController/nextEvent_Default.svg"
    readonly property string mediaController_nextEvent_dim : "qrc:/images/MediaController/nextEvent_dim.svg"
    readonly property string mediaController_nextEvent_hover : "qrc:/images/MediaController/nextEvent_Hover.svg"
    readonly property string mediaController_nextEvent_press : "qrc:/images/MediaController/nextEvent_Press.svg"
    readonly property string mediaController_filter_Disable : "qrc:/images/MediaController/filter_Disable.svg"
    readonly property string mediaController_filter_Default : "qrc:/images/MediaController/filter_Default.svg"
    readonly property string mediaController_filter_Hover : "qrc:/images/MediaController/filter_Hover.svg"
    readonly property string mediaController_filter_Select : "qrc:/images/MediaController/filter_Select.svg"
    readonly property string mediaController_autoskip_n : "qrc:/images/MediaController/icon-autoskip-n.png"
    readonly property string mediaController_autoskip_s : "qrc:/images/MediaController/icon-autoskip-s.png"
    readonly property string mediaController_scroll_left : "qrc:/images/MediaController/scroll_left.svg"
    readonly property string mediaController_scroll_right : "qrc:/images/MediaController/scroll_right.svg"
    readonly property string mediaController_scroll_left_press : "qrc:/images/MediaController/scroll_left_press.svg"
    readonly property string mediaController_scroll_right_press : "qrc:/images/MediaController/scroll_right_press.svg"
    readonly property string mediaController_scroll_left_dim : "qrc:/images/MediaController/scroll_left_dim.svg"
    readonly property string mediaController_scroll_right_dim : "qrc:/images/MediaController/scroll_right_dim.svg"
    readonly property string mediaController_scroll_mediaPos : "qrc:/images/MediaController/scroll_mediaPos.svg"
    readonly property string mediaController_scroll_mediaPos_press : "qrc:/images/MediaController/scroll_mediaPos_press.svg"
    readonly property string mediaController_bookmark : "qrc:/images/MediaController/bookmark.svg"
    readonly property string mediaController_bookmark_clicked : "qrc:/images/MediaController/bookmark_clicked.svg"
    readonly property string mediaController_switch_on : "qrc:/images/MediaController/switch_on.svg"
    readonly property string mediaController_switch_off : "qrc:/images/MediaController/switch_off.svg"
    readonly property string mediaController_range_left : "qrc:/images/MediaController/timelineRange_left.svg"
    readonly property string mediaController_range_right : "qrc:/images/MediaController/timelineRange_right.svg"
    readonly property string mediaController_range : "qrc:/images/MediaController/timelineRange.svg"
    readonly property string mediaController_close_default : "qrc:/images/MediaController/close_Default.svg"
    readonly property string mediaController_close_hover : "qrc:/images/MediaController/close_Hover.svg"
    readonly property string mediaController_close_press : "qrc:/images/MediaController/close_Press.svg"
    readonly property string mediaController_delete_default : "qrc:/images/MediaController/delete_Default.svg"
    readonly property string mediaController_delete_hover : "qrc:/images/MediaController/delete_Hover.svg"
    readonly property string mediaController_delete_press : "qrc:/images/MediaController/delete_Press.svg"
    readonly property string mediaController_live : "qrc:/images/MediaController/timeline_live.svg"
    readonly property string mediaController_playback : "qrc:/images/MediaController/timeline_playback.svg"
    readonly property string mediaController_livePlayback_dim : "qrc:/images/MediaController/timeline_liveplayback_dim.svg"
    readonly property string mediaController_thumbnail_Disable : "qrc:/images/MediaController/thumbnail_Disable.svg"
    readonly property string mediaController_thumbnail_Disable_On : "qrc:/images/MediaController/thumbnail_Disable_On.svg"
    readonly property string mediaController_thumbnail_Default : "qrc:/images/MediaController/thumbnail_Default.svg"
    readonly property string mediaController_thumbnail_Hover : "qrc:/images/MediaController/thumbnail_Hover.svg"
    readonly property string mediaController_thumbnail_Select : "qrc:/images/MediaController/thumbnail_Select.svg"
    readonly property string mediaController_link_Disable : "qrc:/images/MediaController/link_Disable.svg"
    readonly property string mediaController_link_Disable_linked : "qrc:/images/MediaController/link_Disable_linked.svg"
    readonly property string mediaController_link_Default : "qrc:/images/MediaController/link_Default.svg"
    readonly property string mediaController_link_Hover : "qrc:/images/MediaController/link_Hover.svg"
    readonly property string mediaController_link_Select : "qrc:/images/MediaController/link_Select.svg"
    readonly property string mediaController_multiTimeline_Disable : "qrc:/images/MediaController/multiTimeline_Disable.svg"
    readonly property string mediaController_multiTimeline_Default : "qrc:/images/MediaController/multiTimeline_Default.svg"
    readonly property string mediaController_multiTimeline_Hover : "qrc:/images/MediaController/multiTimeline_Hover.svg"
    readonly property string mediaController_multiTimeline_Select : "qrc:/images/MediaController/multiTimeline_Select.svg"
    readonly property string mediaController_overlappedMask : "qrc:/images/MediaController/overlappedMask.svg"
    readonly property string recordType_continuous : "qrc:/WisenetStyle/Icon/Event/recContinuous_Default.svg"
    readonly property string recordType_manual : "qrc:/WisenetStyle/Icon/Event/recManual_Default.svg"
    readonly property string recordType_dummy : "qrc:/WisenetStyle/Icon/Event/dummy_Default.svg"
    readonly property string recordType_alarmIn : "qrc:/WisenetStyle/Icon/Event/alarmIn_Default.svg"
    readonly property string recordType_iva : "qrc:/WisenetStyle/Icon/Event/iva_Default.svg"
    readonly property string recordType_motion : "qrc:/WisenetStyle/Icon/Event/motion_Default.svg"
    readonly property string recordType_face : "qrc:/WisenetStyle/Icon/Event/face_Default.svg"
    readonly property string recordType_tampering : "qrc:/WisenetStyle/Icon/Event/tampering_Default.svg"
    readonly property string recordType_audio : "qrc:/WisenetStyle/Icon/Event/audio_Default.svg"
    readonly property string recordType_tracking : "qrc:/WisenetStyle/Icon/Event/tracking_Default.svg"
    readonly property string recordType_defocus : "qrc:/WisenetStyle/Icon/Event/defocus_Default.svg"
    readonly property string recordType_fog : "qrc:/WisenetStyle/Icon/Event/fog_Default.svg"
    readonly property string recordType_soundClassification : "qrc:/WisenetStyle/Icon/Event/soundClassification_Default.svg"
    readonly property string recordType_videoLoss : "qrc:/WisenetStyle/Icon/Event/videoLoss_Default.svg"
    readonly property string recordType_shock : "qrc:/WisenetStyle/Icon/Event/shock_Default.svg"
    readonly property string recordType_temperature : "qrc:/WisenetStyle/Icon/Event/temperature_Default.svg"
    readonly property string recordType_boxTemperature : "qrc:/WisenetStyle/Icon/Event/boxTemperature_Default.svg"
    readonly property string recordType_objectVehicle : "qrc:/WisenetStyle/Icon/Event/objectVehicle_Default.svg"
    readonly property string recordType_objectFace : "qrc:/WisenetStyle/Icon/Event/objectFace_Default.svg"
    readonly property string recordType_objectPerson : "qrc:/WisenetStyle/Icon/Event/objectPerson_Default.svg"
    readonly property string recordType_faceRecognition : "qrc:/WisenetStyle/Icon/Event/faceRecognition_Default.svg"
    readonly property string recordType_objectLPR : "qrc:/WisenetStyle/Icon/Event/objectLPR_Default.svg"


    // Set Password
    readonly property string show_password_normal : "qrc:/WisenetStyle/Icon/Password/show_password_normal.svg"
    readonly property string show_password_hover : "qrc:/WisenetStyle/Icon/Password/show_password_hover.svg"
    readonly property string show_password_dim : "qrc:/WisenetStyle/Icon/Password/show_password_dim.svg"
    readonly property string hide_password_normal : "qrc:/WisenetStyle/Icon/Password/hide_password_normal.svg"
    readonly property string hide_password_hover : "qrc:/WisenetStyle/Icon/Password/hide_password_hover.svg"
    readonly property string hide_password_dim : "qrc:/WisenetStyle/Icon/Password/hide_password_dim.svg"
    readonly property string info_normal : "qrc:/WisenetStyle/Icon/Password/info_normal.svg"
    readonly property string info_disabled : "qrc:/WisenetStyle/Icon/Password/info_disabled.svg"
    readonly property string info_pressed : "qrc:/WisenetStyle/Icon/Password/info_pressed.svg"

    // CheckBox
    readonly property string check_on : "qrc:/WisenetStyle/Icon/check_on.svg"
    readonly property string check_on_press : "qrc:/WisenetStyle/Icon/check_on_press.svg"
    readonly property string check_on_dim : "qrc:/WisenetStyle/Icon/check_on_dim.svg"
    readonly property string check_off : "qrc:/WisenetStyle/Icon/check_off.svg"
    readonly property string check_off_press : "qrc:/WisenetStyle/Icon/check_off_press.svg"
    readonly property string check_off_dim : "qrc:/WisenetStyle/Icon/check_off_dim.svg"
    readonly property string check_partial : "qrc:/WisenetStyle/Icon/check_partial.svg"

    //TableView
    readonly property string filter : "qrc:/WisenetStyle/Icon/Table/filter.png"
    readonly property string search : "qrc:/WisenetStyle/Icon/search.png"

    //TreeView
    readonly property string resource_tree_branch_expanded : "qrc:/WisenetStyle/Icon/Tree/resource-tree-branch-expanded.svg"
    readonly property string resource_tree_branch_collapsed :"qrc:/WisenetStyle/Icon/Tree/resource-tree-branch-collapsed.svg"
    readonly property string tree_branch_expanded : "qrc:/WisenetStyle/Icon/Tree/tree-branch-expanded.svg"
    readonly property string tree_branch_collapsed :"qrc:/WisenetStyle/Icon/Tree/tree-branch-collapsed.svg"

    //WisenetAllDeviceCheckBox
    readonly property string circle_check_normal : "qrc:/WisenetStyle/Icon/circle-check-normal.svg"
    readonly property string circle_check_hover : "qrc:/WisenetStyle/Icon/circle-check-hover.svg"
    readonly property string circle_check_select : "qrc:/WisenetStyle/Icon/circle-check-select.svg"

    readonly property string all_device_normal : "qrc:/WisenetStyle/Icon/Event/allDeviceDefault.svg"
    readonly property string all_device_hover : "qrc:/WisenetStyle/Icon/Event/allDeviceOver.svg"
    readonly property string all_device_select : "qrc:/WisenetStyle/Icon/Event/allDeviceSelect.svg"

    readonly property string all_event_normal : "qrc:/WisenetStyle/Icon/Event/all_event_default.svg"
    readonly property string all_event_hover : "qrc:/WisenetStyle/Icon/Event/all_event_hover.svg"
    readonly property string all_event_select : "qrc:/WisenetStyle/Icon/Event/all_event_select.svg"

    // Calendar
    readonly property string calendar_prev_month : "qrc:/WisenetStyle/Icon/Calendar/calendar_prev_month.svg"
    readonly property string calendar_prev_month_over : "qrc:/WisenetStyle/Icon/Calendar/calendar_prev_month_over.svg"
    readonly property string calendar_prev_month_press : "qrc:/WisenetStyle/Icon/Calendar/calendar_prev_month_press.svg"
    readonly property string calendar_prev_month_dim : "qrc:/WisenetStyle/Icon/Calendar/calendar_prev_month_dim.svg"
    readonly property string calendar_next_month : "qrc:/WisenetStyle/Icon/Calendar/calendar_next_month.svg"
    readonly property string calendar_next_month_over : "qrc:/WisenetStyle/Icon/Calendar/calendar_next_month_over.svg"
    readonly property string calendar_next_month_press : "qrc:/WisenetStyle/Icon/Calendar/calendar_next_month_press.svg"
    readonly property string calendar_next_month_dim : "qrc:/WisenetStyle/Icon/Calendar/calendar_next_month_dim.svg"
    readonly property string calendar_Default : "qrc:/WisenetStyle/Icon/Calendar/calendar_Default.svg"
    readonly property string calendar_Disable : "qrc:/WisenetStyle/Icon/Calendar/calendar_Disable.svg"
    readonly property string calendar_Hover : "qrc:/WisenetStyle/Icon/Calendar/calendar_Hover.svg"
    readonly property string calendar_Select : "qrc:/WisenetStyle/Icon/Calendar/calendar_Select.svg"
    readonly property string calendar_today : "qrc:/WisenetStyle/Icon/Calendar/calendar_today.svg"
    readonly property string calendar_today_selected : "qrc:/WisenetStyle/Icon/Calendar/calendar_today_selected.svg"

    //Sequence
    readonly property string sequence_add : "qrc:/WisenetStyle/Icon/Sequence/sequence_add_button.svg"
    readonly property string sequence_remove : "qrc:/WisenetStyle/Icon/Sequence/sequence_remove_button.svg"

    readonly property string sequence_edit_default : "qrc:/WisenetStyle/Icon/Sequence/sequence_edit_default.svg"
    readonly property string sequence_edit_select : "qrc:/WisenetStyle/Icon/Sequence/sequence_edit_select.svg"
    readonly property string sequence_edit_hover : "qrc:/WisenetStyle/Icon/Sequence/sequence_edit_hover.svg"
    readonly property string sequence_edit_dim : "qrc:/WisenetStyle/Icon/Sequence/sequence_edit_dim.svg"

    readonly property string sequence_new_window_default : "qrc:/WisenetStyle/Icon/Sequence/sequence_new_window_default.svg"
    readonly property string sequence_new_window_press : "qrc:/WisenetStyle/Icon/Sequence/sequence_new_window_press.svg"
    readonly property string sequence_new_window_hover : "qrc:/WisenetStyle/Icon/Sequence/sequence_new_window_hover.svg"
    readonly property string sequence_new_window_dim : "qrc:/WisenetStyle/Icon/Sequence/sequence_new_window_dim.svg"

    readonly property string move_up_normal : "qrc:/WisenetStyle/Icon/Sequence/move_up_normal.svg"
    readonly property string move_up_dim : "qrc:/WisenetStyle/Icon/Sequence/move_up_dim.svg"
    readonly property string move_down_normal : "qrc:/WisenetStyle/Icon/Sequence/move_down_normal.svg"
    readonly property string move_down_dim : "qrc:/WisenetStyle/Icon/Sequence/move_down_dim.svg"

    readonly property string sequence_main_icon_default : "qrc:/WisenetStyle/Icon/Sequence/sequence_main_icon_default.svg"
    readonly property string sequence_main_icon_select : "qrc:/WisenetStyle/Icon/Sequence/sequence_main_icon_select.svg"
    readonly property string sequence_main_icon_hover : "qrc:/WisenetStyle/Icon/Sequence/sequence_main_icon_hover.svg"
    readonly property string sequence_main_icon_dim : "qrc:/WisenetStyle/Icon/Sequence/sequence_main_icon_dim.svg"

    readonly property string sequence_play : "qrc:/WisenetStyle/Icon/Sequence/sequence_play.svg"
    readonly property string sequence_pause : "qrc:/WisenetStyle/Icon/Sequence/sequence_pause.svg"

    readonly property string spin_up : "qrc:/WisenetStyle/Icon/Sequence/spin_up.svg"
    readonly property string spin_down : "qrc:/WisenetStyle/Icon/Sequence/spin_down.svg"

    //setup
    readonly property string setup_delete_default : "qrc:/WisenetStyle/Icon/Setup/delete-default.svg"
    readonly property string setup_delete_press : "qrc:/WisenetStyle/Icon/Setup/delete-press.svg"
    readonly property string setup_delete_hover : "qrc:/WisenetStyle/Icon/Setup/delete-hover.svg"

    readonly property string setup_add_default : "qrc:/WisenetStyle/Icon/Setup/add-default.svg"
    readonly property string setup_add_press : "qrc:/WisenetStyle/Icon/Setup/add-press.svg"
    readonly property string setup_add_hover : "qrc:/WisenetStyle/Icon/Setup/add-hover.svg"

    readonly property string setup_file_remove_default : "qrc:/WisenetStyle/Icon/Setup/fileRemoveDefault.svg"
    readonly property string setup_file_select_default : "qrc:/WisenetStyle/Icon/Setup/fileSelectDefault.svg"

    readonly property string setup_add_DDNS_P2P : "qrc:/WisenetStyle/Icon/Setup/addDdnsP2p.svg"
    readonly property string setup_add_device : "qrc:/WisenetStyle/Icon/Setup/addDevice.svg"
    readonly property string setup_add_user : "qrc:/WisenetStyle/Icon/Setup/addUser.svg"
    readonly property string setup_add_usergroup : "qrc:/WisenetStyle/Icon/Setup/addUserGroup.svg"
    readonly property string setup_add_eventrule : "qrc:/WisenetStyle/Icon/Setup/addEventRule.svg"
    readonly property string setup_language : "qrc:/WisenetStyle/Icon/Setup/language.svg"

    readonly property string setup_left_arrow_normal: "qrc:/WisenetStyle/Icon/putin-left-normal.svg"
    readonly property string setup_left_arrow_hover: "qrc:/WisenetStyle/Icon/putin-left-hover.svg"
    readonly property string setup_right_arrow_normal: "qrc:/WisenetStyle/Icon/putin-right-normal.svg"
    readonly property string setup_right_arrow_hover: "qrc:/WisenetStyle/Icon/putin-right-hover.svg"

    readonly property string setup_license_right_key: "qrc:/WisenetStyle/Icon/Setup/license_right_key.svg"
    readonly property string setup_license_wrong_key: "qrc:/WisenetStyle/Icon/Setup/license_wrong_key.svg"

    //setup - device
    readonly property string setup_device_question_normal : "qrc:/WisenetStyle/Icon/Setup/Device/question_normal.svg"
    readonly property string setup_device_question_hover : "qrc:/WisenetStyle/Icon/Setup/Device/question_hover.svg"
    readonly property string setup_device_question_press : "qrc:/WisenetStyle/Icon/Setup/Device/question_press.svg"

    readonly property string setup_device_resetName_normal : "qrc:/WisenetStyle/Icon/Setup/Device/resetName-default.svg"
    readonly property string setup_device_resetName_hover : "qrc:/WisenetStyle/Icon/Setup/Device/resetName-hover.svg"
    readonly property string setup_device_resetName_press : "qrc:/WisenetStyle/Icon/Setup/Device/resetName-press.svg"


    //setup - user
    readonly property string setup_user_permission_audio_normal : "qrc:/WisenetStyle/Icon/Setup/User/permission_audio_normal.svg"
    readonly property string setup_user_permission_backup_normal : "qrc:/WisenetStyle/Icon/Setup/User/permission_backup_normal.svg"
    readonly property string setup_user_permission_localRecording_normal : "qrc:/WisenetStyle/Icon/Setup/User/permission_localRecording_normal.svg"
    readonly property string setup_user_permission_ptz_normal : "qrc:/WisenetStyle/Icon/Setup/User/permission_ptz_normal.svg"
    readonly property string setup_user_permission_search_normal : "qrc:/WisenetStyle/Icon/Setup/User/permission_search_normal.svg"
    readonly property string setup_user_permission_mic_normal : "qrc:/WisenetStyle/Icon/Setup/User/permission_mic_normal.svg"

    //tree

    readonly property string tree_nvr_normal : "qrc:/WisenetStyle/Icon/Tree/tree_nvr_normal.svg"
    readonly property string tree_nvr_disconnect :  "qrc:/WisenetStyle/Icon/Tree/tree_nvr_dim.svg"
    readonly property string tree_side_home : "qrc:/WisenetStyle/Icon/Tree/side_home.svg"
    readonly property string tree_side_device : "qrc:/WisenetStyle/Icon/Tree/side_device.svg"
    readonly property string tree_side_user :  "qrc:/WisenetStyle/Icon/Tree/side_user.svg"
    readonly property string tree_side_event : "qrc:/WisenetStyle/Icon/Tree/side_event.svg"
    readonly property string tree_side_log :  "qrc:/WisenetStyle/Icon/Tree/side_log.svg"
    readonly property string tree_side_system : "qrc:/WisenetStyle/Icon/Tree/side_system.svg"
    readonly property string tree_fold :  "qrc:/WisenetStyle/Icon/Tree/Fold.svg"
    readonly property string tree_unfold : "qrc:/WisenetStyle/Icon/Tree/Unfold.svg"
    readonly property string textLink : "qrc:/WisenetStyle/Icon/Setup/textlink.svg"
    readonly property string textLink_hover : "qrc:/WisenetStyle/Icon/Setup/textlink-hover.svg"
    readonly property string textLink_press : "qrc:/WisenetStyle/Icon/Setup/textlink-press.svg"


    // popup Window
    readonly property string popup_close_default : "qrc:/WisenetStyle/Icon/PopupWindow/close_Default.svg"
    readonly property string popup_close_hover : "qrc:/WisenetStyle/Icon/PopupWindow/close_Hover.svg"
    readonly property string popup_close_press : "qrc:/WisenetStyle/Icon/PopupWindow/close_Press.svg"
    readonly property string popup_minimize_default : "qrc:/WisenetStyle/Icon/PopupWindow/minimize_Default.svg"
    readonly property string popup_minimize_hover : "qrc:/WisenetStyle/Icon/PopupWindow/minimize_Hover.svg"
    readonly property string popup_minimize_press : "qrc:/WisenetStyle/Icon/PopupWindow/minimize_Press.svg"
    readonly property string popup_maximize_default : "qrc:/WisenetStyle/Icon/PopupWindow/maximize_Default.svg"
    readonly property string popup_maximize_hover : "qrc:/WisenetStyle/Icon/PopupWindow/maximize_Hover.svg"
    readonly property string popup_maximize_press : "qrc:/WisenetStyle/Icon/PopupWindow/maximize_Press.svg"
    readonly property string popup_normalize_default : "qrc:/WisenetStyle/Icon/PopupWindow/normalize_Default.svg"
    readonly property string popup_normalize_hover : "qrc:/WisenetStyle/Icon/PopupWindow/normalize_Hover.svg"
    readonly property string popup_normalize_press : "qrc:/WisenetStyle/Icon/PopupWindow/normalize_Press.svg"

    // object search
    readonly property string object_search_open_menu_default : "qrc:/WisenetStyle/Icon/ObjectSearch/open_menu_default.svg"
    readonly property string object_search_open_menu_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/open_menu_hover.svg"
    readonly property string object_search_open_menu_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/open_menu_selected.svg"

    readonly property string object_search_filter_button_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter_button_default.svg"
    readonly property string object_search_filter_button_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter_button_dim.svg"
    readonly property string object_search_filter_button_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter_button_hover.svg"
    readonly property string object_search_filter_button_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter_button_selected.svg"
    readonly property string object_search_filter_button_selected_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter_button_selectover.svg"

    readonly property string object_search_flag_filled_default : "qrc:/WisenetStyle/Icon/ObjectSearch/flag_filled_default.svg"
    readonly property string object_search_flag_filled_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/flag_filled_hover.svg"
    readonly property string object_search_flag_filled_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/flag_filled_selected.svg"

    readonly property string object_search_flag_view_default : "qrc:/WisenetStyle/Icon/ObjectSearch/flag_view_default.svg"
    readonly property string object_search_flag_view_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/flag_view_dim.svg"
    readonly property string object_search_flag_view_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/flag_view_hover.svg"
    readonly property string object_search_flag_view_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/flag_view_selected.svg"

    readonly property string object_search_grid_view_default : "qrc:/WisenetStyle/Icon/ObjectSearch/grid_view_default.svg"
    readonly property string object_search_grid_view_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/grid_view_dim.svg"
    readonly property string object_search_grid_view_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/grid_view_hover.svg"
    readonly property string object_search_grid_view_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/grid_view_selected.svg"

    readonly property string object_search_image_export_default : "qrc:/WisenetStyle/Icon/ObjectSearch/image_export_default.svg"
    readonly property string object_search_image_export_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/image_export_dim.svg"
    readonly property string object_search_image_export_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/image_export_hover.svg"
    readonly property string object_search_image_export_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/image_export_selected.svg"

    readonly property string object_search_thumbnail_view_default : "qrc:/WisenetStyle/Icon/ObjectSearch/thumbnail_view_default.svg"
    readonly property string object_search_thumbnail_view_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/thumbnail_view_dim.svg"
    readonly property string object_search_thumbnail_view_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/thumbnail_view_hover.svg"
    readonly property string object_search_thumbnail_view_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/thumbnail_view_selected.svg"

    readonly property string object_search_zoom_in : "qrc:/WisenetStyle/Icon/ObjectSearch/zoom_in.svg"
    readonly property string object_search_zoom_out : "qrc:/WisenetStyle/Icon/ObjectSearch/zoom_out.svg"

    readonly property string object_search_add_bookmark_default : "qrc:/WisenetStyle/Icon/ObjectSearch/add_bookmark_default.svg"
    readonly property string object_search_add_bookmark_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/add_bookmark_hover.svg"

    readonly property string object_search_fixed_default : "qrc:/WisenetStyle/Icon/ObjectSearch/fixed_default.svg"
    readonly property string object_search_fixed_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/fixed_hover.svg"
    readonly property string object_search_unfixed_default : "qrc:/WisenetStyle/Icon/ObjectSearch/unfixed_default.svg"
    readonly property string object_search_unfixed_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/unfixed_hover.svg"

    readonly property string object_search_filter_checked : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/filter_checked.svg"
    readonly property string object_search_filter_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/filter_hover.svg"

    readonly property string object_search_filter_male_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/male_default.svg"
    readonly property string object_search_filter_male_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/male_dim.svg"
    readonly property string object_search_filter_male_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/male_hover.svg"
    readonly property string object_search_filter_male_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/male_selected.svg"
    readonly property string object_search_filter_male_selected_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/male_selectover.svg"

    readonly property string object_search_filter_female_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/female_default.svg"
    readonly property string object_search_filter_female_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/female_dim.svg"
    readonly property string object_search_filter_female_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/female_hover.svg"
    readonly property string object_search_filter_female_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/female_selected.svg"
    readonly property string object_search_filter_female_selected_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/female_selectover.svg"

    readonly property string object_search_filter_bag_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/bag_default.svg"
    readonly property string object_search_filter_bag_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/bag_dim.svg"
    readonly property string object_search_filter_bag_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/bag_hover.svg"
    readonly property string object_search_filter_bag_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/bag_selected.svg"
    readonly property string object_search_filter_bag_selected_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/bag_selectover.svg"

    readonly property string object_search_filter_no_bag_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/no_bag_default.svg"
    readonly property string object_search_filter_no_bag_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/no_bag_dim.svg"
    readonly property string object_search_filter_no_bag_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/no_bag_hover.svg"
    readonly property string object_search_filter_no_bag_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/no_bag_selected.svg"
    readonly property string object_search_filter_no_bag_selected_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/no_bag_selectover.svg"

    readonly property string object_search_filter_young_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/young_default.svg"
    readonly property string object_search_filter_young_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/young_dim.svg"
    readonly property string object_search_filter_young_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/young_hover.svg"
    readonly property string object_search_filter_young_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/young_selected.svg"
    readonly property string object_search_filter_young_selected_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/young_selectover.svg"

    readonly property string object_search_filter_adult_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/adult_default.svg"
    readonly property string object_search_filter_adult_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/adult_dim.svg"
    readonly property string object_search_filter_adult_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/adult_hover.svg"
    readonly property string object_search_filter_adult_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/adult_selected.svg"
    readonly property string object_search_filter_adult_selected_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/adult_selectover.svg"

    readonly property string object_search_filter_middle_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/middle_default.svg"
    readonly property string object_search_filter_middle_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/middle_dim.svg"
    readonly property string object_search_filter_middle_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/middle_hover.svg"
    readonly property string object_search_filter_middle_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/middle_selected.svg"
    readonly property string object_search_filter_middle_selected_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/middle_selectover.svg"

    readonly property string object_search_filter_senior_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/senior_default.svg"
    readonly property string object_search_filter_senior_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/senior_dim.svg"
    readonly property string object_search_filter_senior_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/senior_hover.svg"
    readonly property string object_search_filter_senior_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/senior_selected.svg"
    readonly property string object_search_filter_senior_selected_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/senior_selectover.svg"

    readonly property string object_search_filter_mask_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/mask_default.svg"
    readonly property string object_search_filter_mask_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/mask_dim.svg"
    readonly property string object_search_filter_mask_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/mask_hover.svg"
    readonly property string object_search_filter_mask_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/mask_selected.svg"
    readonly property string object_search_filter_mask_selected_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/mask_selectover.svg"

    readonly property string object_search_filter_no_mask_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/no_mask_default.svg"
    readonly property string object_search_filter_no_mask_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/no_mask_dim.svg"
    readonly property string object_search_filter_no_mask_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/no_mask_hover.svg"
    readonly property string object_search_filter_no_mask_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/no_mask_selected.svg"
    readonly property string object_search_filter_no_mask_selected_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/no_mask_selectover.svg"

    readonly property string object_search_filter_glasses_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/glasses_default.svg"
    readonly property string object_search_filter_glasses_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/glasses_dim.svg"
    readonly property string object_search_filter_glasses_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/glasses_hover.svg"
    readonly property string object_search_filter_glasses_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/glasses_selected.svg"
    readonly property string object_search_filter_glasses_selected_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/glasses_selectover.svg"

    readonly property string object_search_filter_no_glasses_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/no_glasses_default.svg"
    readonly property string object_search_filter_no_glasses_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/no_glasses_dim.svg"
    readonly property string object_search_filter_no_glasses_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/no_glasses_hover.svg"
    readonly property string object_search_filter_no_glasses_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/no_glasses_selected.svg"
    readonly property string object_search_filter_no_glasses_selected_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/no_glasses_selectover.svg"

    readonly property string object_search_filter_car_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/car_default.svg"
    readonly property string object_search_filter_car_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/car_dim.svg"
    readonly property string object_search_filter_car_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/car_hover.svg"
    readonly property string object_search_filter_car_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/car_selected.svg"
    readonly property string object_search_filter_car_selected_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/car_selectover.svg"

    readonly property string object_search_filter_bus_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/bus_default.svg"
    readonly property string object_search_filter_bus_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/bus_dim.svg"
    readonly property string object_search_filter_bus_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/bus_hover.svg"
    readonly property string object_search_filter_bus_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/bus_selected.svg"
    readonly property string object_search_filter_bus_selected_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/bus_selectover.svg"

    readonly property string object_search_filter_truck_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/truck_default.svg"
    readonly property string object_search_filter_truck_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/truck_dim.svg"
    readonly property string object_search_filter_truck_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/truck_hover.svg"
    readonly property string object_search_filter_truck_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/truck_selected.svg"
    readonly property string object_search_filter_truck_selected_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/truck_selectover.svg"

    readonly property string object_search_filter_motorcycle_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/motorcycle_default.svg"
    readonly property string object_search_filter_motorcycle_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/motorcycle_dim.svg"
    readonly property string object_search_filter_motorcycle_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/motorcycle_hover.svg"
    readonly property string object_search_filter_motorcycle_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/motorcycle_selected.svg"
    readonly property string object_search_filter_motorcycle_selected_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/motorcycle_selectover.svg"

    readonly property string object_search_filter_bicycle_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/bicycle_default.svg"
    readonly property string object_search_filter_bicycle_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/bicycle_dim.svg"
    readonly property string object_search_filter_bicycle_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/bicycle_hover.svg"
    readonly property string object_search_filter_bicycle_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/bicycle_selected.svg"
    readonly property string object_search_filter_bicycle_selected_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/bicycle_selectover.svg"

    readonly property string object_search_filter_color_black_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_black_default.svg"
    readonly property string object_search_filter_color_black_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_black_dim.svg"
    readonly property string object_search_filter_color_black_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_black_hover.svg"

    readonly property string object_search_filter_color_gray_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_gray_default.svg"
    readonly property string object_search_filter_color_gray_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_gray_dim.svg"
    readonly property string object_search_filter_color_gray_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_gray_hover.svg"

    readonly property string object_search_filter_color_white_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_white_default.svg"
    readonly property string object_search_filter_color_white_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_white_dim.svg"
    readonly property string object_search_filter_color_white_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_white_hover.svg"

    readonly property string object_search_filter_color_red_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_red_default.svg"
    readonly property string object_search_filter_color_red_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_red_dim.svg"
    readonly property string object_search_filter_color_red_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_red_hover.svg"

    readonly property string object_search_filter_color_orange_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_orange_default.svg"
    readonly property string object_search_filter_color_orange_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_orange_dim.svg"
    readonly property string object_search_filter_color_orange_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_orange_hover.svg"

    readonly property string object_search_filter_color_yellow_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_yellow_default.svg"
    readonly property string object_search_filter_color_yellow_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_yellow_dim.svg"
    readonly property string object_search_filter_color_yellow_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_yellow_hover.svg"

    readonly property string object_search_filter_color_green_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_green_default.svg"
    readonly property string object_search_filter_color_green_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_green_dim.svg"
    readonly property string object_search_filter_color_green_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_green_hover.svg"

    readonly property string object_search_filter_color_blue_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_blue_default.svg"
    readonly property string object_search_filter_color_blue_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_blue_dim.svg"
    readonly property string object_search_filter_color_blue_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_blue_hover.svg"

    readonly property string object_search_filter_color_purple_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_purple_default.svg"
    readonly property string object_search_filter_color_purple_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_purple_dim.svg"
    readonly property string object_search_filter_color_purple_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/color_purple_hover.svg"

    readonly property string object_search_filter_person_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/person_default.svg"
    readonly property string object_search_filter_person_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/person_dim.svg"
    readonly property string object_search_filter_person_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/person_hover.svg"
    readonly property string object_search_filter_person_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/person_selected.svg"

    readonly property string object_search_filter_face_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/face_default.svg"
    readonly property string object_search_filter_face_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/face_dim.svg"
    readonly property string object_search_filter_face_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/face_hover.svg"
    readonly property string object_search_filter_face_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/face_selected.svg"

    readonly property string object_search_filter_vehicle_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/vehicle_default.svg"
    readonly property string object_search_filter_vehicle_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/vehicle_dim.svg"
    readonly property string object_search_filter_vehicle_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/vehicle_hover.svg"
    readonly property string object_search_filter_vehicle_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/vehicle_selected.svg"

    readonly property string object_search_filter_ocr_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/ocr_default.svg"
    readonly property string object_search_filter_ocr_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/ocr_dim.svg"
    readonly property string object_search_filter_ocr_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/ocr_hover.svg"
    readonly property string object_search_filter_ocr_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/ocr_selected.svg"

    readonly property string object_search_filter_fold : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/fold.svg"
    readonly property string object_search_filter_unfold : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/unfold.svg"

    readonly property string object_search_filter_clear_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/clear_default.svg"
    readonly property string object_search_filter_clear_dim : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/clear_dim.svg"
    readonly property string object_search_filter_clear_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/clear_hover.svg"
    readonly property string object_search_filter_clear_selected : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/clear_selected.svg"

    readonly property string object_search_filter_info_default : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/info_default.svg"
    readonly property string object_search_filter_info_hover : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/info_hover.svg"

    readonly property string object_search_filter_person_title : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/person_title.svg"
    readonly property string object_search_filter_face_title : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/face_title.svg"
    readonly property string object_search_filter_vehicle_title : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/vehicle_title.svg"
    readonly property string object_search_filter_lpr_title : "qrc:/WisenetStyle/Icon/ObjectSearch/filter/lpr_title.svg"

    //EventRule

    // EventSchedule
    readonly property string eventSchedule_arrowtip_diagonal : "qrc:/WisenetStyle/Icon/Setup/Event/arrowtip_diagonal.svg"
    readonly property string eventSchedule_arrowtip_down : "qrc:/WisenetStyle/Icon/Setup/Event/arrowtip_down.svg"
    readonly property string eventSchedule_arrowtip_right : "qrc:/WisenetStyle/Icon/Setup/Event/arrowtip_right.svg"


    // EventSearch
    readonly property string eventBookmark_unchecked_default : "qrc:/WisenetStyle/Icon/eventBookmark_unchecked_default.svg"
    readonly property string eventBookmark_unchecked_hover : "qrc:/WisenetStyle/Icon/eventBookmark_unchecked_hover.svg"
    readonly property string eventBookmark_checked_default : "qrc:/WisenetStyle/Icon/eventBookmark_checked_default.svg"
    readonly property string eventBookmark_checked_hover : "qrc:/WisenetStyle/Icon/eventBookmark_checked_hover.svg"

    // Verifying digital signature
    readonly property string verify_fail_default : "qrc:/WisenetStyle/Icon/Tree/tree_verify_fail_default.svg"
    readonly property string verify_fail_hover : "qrc:/WisenetStyle/Icon/Tree/tree_verify_fail_hover.svg"
    readonly property string verify_success_default : "qrc:/WisenetStyle/Icon/Tree/tree_verify_success_default.svg"
    readonly property string verify_success_hover : "qrc:/WisenetStyle/Icon/Tree/tree_verify_success_hover.svg"
    readonly property string verify_no_default : "qrc:/WisenetStyle/Icon/Tree/tree_verify_no_default.svg"
    readonly property string verify_no_hover : "qrc:/WisenetStyle/Icon/Tree/tree_verify_no_hover.svg"
    readonly property string verifying_default : "qrc:/WisenetStyle/Icon/Tree/tree_verifying_default.svg"
    readonly property string verifying_hover : "qrc:/WisenetStyle/Icon/Tree/tree_verifying_hover.svg"

    // ptz control
    readonly property string ptz_start_default : "qrc:/WisenetStyle/Icon/ptz_play_default.svg"
    readonly property string ptz_start_hover : "qrc:/WisenetStyle/Icon/ptz_play_hover.svg"
    readonly property string ptz_start_selected : "qrc:/WisenetStyle/Icon/ptz_play_selected.svg"
    readonly property string ptz_start_dim : "qrc:/WisenetStyle/Icon/ptz_play_dim.svg"

    readonly property string ptz_stop_default : "qrc:/WisenetStyle/Icon/ptz_pause_default.svg"
    readonly property string ptz_stop_hover : "qrc:/WisenetStyle/Icon/ptz_pause_hover.svg"
    readonly property string ptz_stop_selected : "qrc:/WisenetStyle/Icon/ptz_pause_selected.svg"
    readonly property string ptz_stop_dim : "qrc:/WisenetStyle/Icon/ptz_pause_dim.svg"

    readonly property string checked : "qrc:/WisenetStyle/Icon/Setup/User/ldapok.svg"
    readonly property string checked_hover : "qrc:/WisenetStyle/Icon/Setup/User/ldapok_hover.svg"
}
